### ISSUE TITLE
When the content contains single quotes, the update is wrong

### ISSUE THREAD

**Issue by zswang** [zswang/h5i18n#2]
* config

```yaml
- file: ../button.js
  i18n:
    - lang:
      cn: 汤姆的小猫
      todo: null
    - update:
      cn: 汤姆的小猫
      en: "Tom's kitten"
```

* input

```js
input.value = languages.get('汤姆的小猫<!--{todo}-->');
```

* output

```js
input.value = languages.get('汤姆的小猫<!--{en}Tom's kitten-->');
```

* meet

```js
input.value = languages.get('汤姆的小猫<!--{en}Tom\'s kitten-->');
```
