### ISSUE TITLE
Attribute and content conflict when updating

### ISSUE THREAD

**Issue by zswang** [zswang/h5i18n#3]
* input

```html
<div title="中文属性" data-lang-title="<!--{en}English attribute-->">中文内容<!--{en}English content--></div>
```

* extract

```yaml
- file: temp.html
  i18n:
    - lang:
      cn: 中文属性
      en: English attribute
```

* meet

```yaml
- file: temp.html
  i18n:
    - lang:
      cn: 中文属性
      en: English attribute
    - lang:
      cn: 中文内容
      en: English content
```
